### ISSUE TITLE
Sincronización de equipos

### ISSUE THREAD

**Issue by lorenaruhl** [LabSis/isaai#2]
Hoy depués de dos semanas sincronice los equipos y lo que noté es que sincroniza de a 8 máquinas. Sincronice la cantidad de veces necesarias mientras me daba el mensaje "8 maquinas han cambiado", hasta que me dio el mensaje "ninguna máquina ha cambiado".
Ver si hay algun bloqueo en algun lado que esté limitando la cantidad de equipos a sincronizar.

**Comment by dsbarrionuevo** [comment]
Solucionado quitando límite de 8 máquinas usado en entorno de prueba.
