### ISSUE TITLE
Arreglar máquinas duplicadas

### ISSUE THREAD

**Issue by dsbarrionuevo** [LabSis/isaai#8]
La máquina con hostname "milagroszea" en cliente Linux se repita muchas veces, analizar situación si es debido a fallos en el Cliente Linux del HardwareCollector o del Servidor HardwareCollector (o incluso podría deberse a Isaai dada su configuración para determinar cuándo una máquina es duplicada).
Una vez identificado el por qué, eliminar las máquinas duplicadas de "milagroszea" de la base de datos de ISAAI.

**Comment by milyzc** [comment]
bd limpia.
