### ISSUE TITLE
Login de usuarios

### ISSUE THREAD

**Issue by Gochip** [LabSis/isaai#9]
El login de usuario debería estar hecho con la API aulas a través de LDAP. Consultar para más información.

**Comment by dsbarrionuevo** [comment]
En login.php conectarse usando cURL (de PHP) a tu clon del proyecto https://gitlab.com/LabSis/labsis_api_aulas (que está corriendo el localhost) y en ese mismo usar el método "validar_usuario.php" (sus parámetros de entrada y su salida están especificados en ese .php).
